title: ShadowFiles
description: Investigative OSINT reports exposing corruption across Nigeria.
author:
  name: ShadowFiles
  email: (leave blank or use a burner email)
show_downloads: false
theme: jekyll-theme-cayman
