title: ShadowFiles
description: Investigative OSINT reports exposing corruption across Nigeria.
author:shadow
  name: ShadowFiles
  email: nature000011@protonmail.com
show_downloads: false
theme: jekyll-theme-cayman
